### ISSUE TITLE
Building bb fails with the latest version of GraalVM 21.1.0.r16

### ISSUE THREAD

**Issue by neuromantik33** [babashka/babashka#864]
**version**

babashka v0.4.4-SNAPSHOT

**platform**

Graalvm installed with sdkman : 21.1.0.r16-grl

**problem**

```bash
$ ./script/uberjar
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05, mixed mode, sharing)
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Compiling babashka.curl
Compiling babashka.fs
Compiling babashka.impl.async
Compiling babashka.impl.bencode
Compiling babashka.impl.cheshire
Compiling babashka.impl.classes
Compiling babashka.impl.classpath
Compiling babashka.impl.clojure.core
Compiling babashka.impl.clojure.core.server
Compiling babashka.impl.clojure.data
Compiling babashka.impl.clojure.java.browse
Compiling babashka.impl.clojure.java.io
Compiling babashka.impl.clojure.java.shell
Compiling babashka.impl.clojure.main
Compiling babashka.impl.clojure.spec.alpha
Compiling babashka.impl.clojure.spec.gen.alpha
Compiling babashka.impl.clojure.spec.test.alpha
Compiling babashka.impl.clojure.stacktrace
Compiling babashka.impl.clojure.test
Compiling babashka.impl.clojure.test.check
Compiling babashka.impl.clojure.zip
Compiling babashka.impl.common
Compiling babashka.impl.csv
Compiling babashka.impl.curl
Compiling babashka.impl.data
Compiling babashka.impl.datafy
Compiling babashka.impl.deps
Syntax error compiling . at (borkdude/deps.clj:196:12).
Syntax error (IllegalArgumentException) compiling . at (borkdude/deps.clj:196:12).
More than one matching method found: newFileSystem

Full report at:
/tmp/clojure-13349132107375101896.edn
Compilation failed: Subprocess failed (exit code: 1)
Uberjar aborting because jar failed: Compilation failed: Subprocess failed (exit code: 1)
Error encountered performing task 'do' with profile(s): 'base,system,user,provided,dev,uberjar,jdbc,postgresql,xml,yaml,core-async,csv,transit,httpkit-client,httpkit-server,core-match,hiccup,test-check,rewrite-clj,selmer'
Uberjar aborting because jar failed: Compilation failed: Subprocess failed (exit code: 1)
```

**repro**

```bash
$ Install graalvm using `sdk install java 21.1.0.r16-grl`
$ export GRAALVM_HOME=~/.sdkman/candidates/java/21.1.0.r16-grl/
$ ./script/uberjar
```

**Comment by borkdude** [comment]
Thanks for the issue. I'll keep it open until we upgrade to 21.1.0. Currently the build is done using 21.0.0. There has been some image bloat when upgrading to 21.1.0 which I want to sort out first.

https://github.com/oracle/graal/issues/3280#issuecomment-846402115

**Comment by borkdude** [comment]
Upgraded to 21.1.0, can't reproduce any problems. Feel free to re-open with a repro.

**Comment by neuromantik33** [comment]
Weird I'm still having the issue on my ubuntu 20.04 machine...

```bash
$ ./build-bb.sh 
+ export GRAALVM_HOME=/home/drnick/.sdkman/candidates/java/21.1.0.r16-grl
+ GRAALVM_HOME=/home/drnick/.sdkman/candidates/java/21.1.0.r16-grl
+ export BABASHKA_XMX=-J-Xmx8g
+ BABASHKA_XMX=-J-Xmx8g
+ export BABASHKA_FEATURE_JDBC=true
+ BABASHKA_FEATURE_JDBC=true
+ export BABASHKA_FEATURE_POSTGRESQL=true
+ BABASHKA_FEATURE_POSTGRESQL=true
+ ./script/uberjar
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05, mixed mode, sharing)
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Compiling babashka.main
Syntax error compiling . at (borkdude/deps.clj:196:12).
Syntax error (IllegalArgumentException) compiling . at (borkdude/deps.clj:196:12).
More than one matching method found: newFileSystem

Full report at:
/tmp/clojure-13545889036431754781.edn
Compilation failed: Subprocess failed (exit code: 1)
Uberjar aborting because jar failed: Compilation failed: Subprocess failed (exit code: 1)
Error encountered performing task 'do' with profile(s): 'base,system,user,provided,dev,uberjar,jdbc,postgresql,xml,yaml,core-async,csv,transit,httpkit-client,httpkit-server,core-match,hiccup,test-check,rewrite-clj,selmer'
Uberjar aborting because jar failed: Compilation failed: Subprocess failed (exit code: 1)
$ git status
HEAD detached at v0.4.6
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	build-bb.sh

nothing added to commit but untracked files present (use "git add" to track)
$ uname -a
Linux drnick-xps-15-9500 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05, mixed mode, sharing)
```

**Comment by borkdude** [comment]
Why don't you use the normal 21.1.0 release? What is r16-grl? I am not seeing that on the downloads page.

**Comment by neuromantik33** [comment]
It works with `21.1.0.r11-grl`, no worries. I use [sdkman](https://sdkman.io/) to manage my jdks, sdks, etc...

```bash
$ sdk ls java
================================================================================
Available Java Versions
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
 AdoptOpenJDK  |     | 16.0.1.j9    | adpt    | installed  | 16.0.1.j9-adpt      
               |     | 16.0.1.hs    | adpt    |            | 16.0.1.hs-adpt      
               |     | 11.0.11.j9   | adpt    | installed  | 11.0.11.j9-adpt     
               |     | 11.0.11.hs   | adpt    |            | 11.0.11.hs-adpt     
               |     | 8.0.292.j9   | adpt    | installed  | 8.0.292.j9-adpt     
               |     | 8.0.292.hs   | adpt    |            | 8.0.292.hs-adpt     
 Alibaba       |     | 11.0.9.4     | albba   |            | 11.0.9.4-albba      
               |     | 8.5.5        | albba   |            | 8.5.5-albba         
 Amazon        |     | 16.0.1.9.1   | amzn    |            | 16.0.1.9.1-amzn     
               |     | 11.0.11.9.1  | amzn    |            | 11.0.11.9.1-amzn    
               |     | 8.292.10.1   | amzn    |            | 8.292.10.1-amzn     
 Azul Zulu     |     | 16.0.1       | zulu    |            | 16.0.1-zulu         
               |     | 16.0.1.fx    | zulu    |            | 16.0.1.fx-zulu      
               |     | 11.0.11      | zulu    |            | 11.0.11-zulu        
               |     | 11.0.11.fx   | zulu    |            | 11.0.11.fx-zulu     
               |     | 8.0.292      | zulu    |            | 8.0.292-zulu        
               |     | 8.0.292.fx   | zulu    |            | 8.0.292.fx-zulu     
               |     | 7.0.302      | zulu    |            | 7.0.302-zulu        
               |     | 6.0.119      | zulu    |            | 6.0.119-zulu        
 BellSoft      |     | 16.0.1.fx    | librca  |            | 16.0.1.fx-librca    
               |     | 16.0.1       | librca  |            | 16.0.1-librca       
               |     | 11.0.11.fx   | librca  |            | 11.0.11.fx-librca   
               |     | 11.0.11      | librca  |            | 11.0.11-librca      
               |     | 8.0.292.fx   | librca  |            | 8.0.292.fx-librca   
               |     | 8.0.292      | librca  |            | 8.0.292-librca      
 GraalVM       |     | 21.1.0.r16   | grl     | installed  | 21.1.0.r16-grl      
               | >>> | 21.1.0.r11   | grl     | installed  | 21.1.0.r11-grl      
               |     | 21.1.0.r8    | grl     |            | 21.1.0.r8-grl       
               |     | 21.0.0.2.r11 | grl     |            | 21.0.0.2.r11-grl    
               |     | 21.0.0.2.r8  | grl     |            | 21.0.0.2.r8-grl     
               |     | 20.3.2.r11   | grl     |            | 20.3.2.r11-grl      
               |     | 20.3.2.r8    | grl     |            | 20.3.2.r8-grl       
               |     | 20.3.1.2.r11 | grl     |            | 20.3.1.2.r11-grl    
               |     | 20.3.1.2.r8  | grl     |            | 20.3.1.2.r8-grl     
               |     | 19.3.6.r11   | grl     |            | 19.3.6.r11-grl      
               |     | 19.3.6.r8    | grl     |            | 19.3.6.r8-grl       
               |     | 19.3.5.r11   | grl     |            | 19.3.5.r11-grl      
               |     | 19.3.5.r8    | grl     |            | 19.3.5.r8-grl       
 Java.net      |     | 18.ea.1      | open    |            | 18.ea.1-open        
               |     | 17.ea.26     | open    |            | 17.ea.26-open       
               |     | 17.ea.25     | open    |            | 17.ea.25-open       
               |     | 17.ea.7.lm   | open    |            | 17.ea.7.lm-open     
               |     | 17.ea.3.pma  | open    |            | 17.ea.3.pma-open    
               |     | 16.0.1       | open    |            | 16.0.1-open         
               |     | 11.0.11      | open    |            | 11.0.11-open        
               |     | 11.0.10      | open    |            | 11.0.10-open        
               |     | 11.0.2       | open    |            | 11.0.2-open         
               |     | 8.0.292      | open    |            | 8.0.292-open        
               |     | 8.0.282      | open    |            | 8.0.282-open        
               |     | 8.0.265      | open    |            | 8.0.265-open        
 Mandrel       |     | 21.1.0.0     | mandrel |            | 21.1.0.0-mandrel    
               |     | 20.3.2.0     | mandrel |            | 20.3.2.0-mandrel    
 Microsoft     |     | 16.0.1.9.1   | ms      |            | 16.0.1.9.1-ms       
               |     | 11.0.11.9.1  | ms      |            | 11.0.11.9.1-ms      
 SAP           |     | 16.0.1       | sapmchn |            | 16.0.1-sapmchn      
               |     | 11.0.11      | sapmchn |            | 11.0.11-sapmchn     
 TravaOpenJDK  |     | 11.0.9       | trava   |            | 11.0.9-trava        
               |     | 8.0.232      | trava   |            | 8.0.232-trava       
================================================================================
Use the Identifier for installation:

    $ sdk install java 11.0.3.hs-adpt
================================================================================
```
